banner_equipment :-
write('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n'),
write('%   _____ ___  _   _ ___ ____  __  __ _____ _   _ _____   %\n'),
write('%  | ____/ _ || | | |_ _|  _ ||  ||  | ____| | | |_   _|  %\n'),
write('%  |  _|| | | | | | || || |_) | |||  |  _| |  || | | |    %\n'),
write('%  | |__| |_| | |_| || ||  __/| |  | | |___| ||  | | |    %\n'),
write('%  |_____|__|_||___/|___|_|   |_|  |_|_____|_| |_| |_|    %\n'),
write('%                                                         %\n'),
write('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n').

banner_special :-
write('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n'),
write('%   ____  ____  _____ ____ ___    _    _       %\n'),
write('%  / ___||  _ || ____/ ___|_ _|  / |  | |      %\n'),
write('%  |___ || |_) |  _|| |    | |  / _ | | |      %\n'),
write('%   ___) |  __/| |__| |___ | | / ___ || |___   %\n'),
write('%  |____/|_|   |_____|____|___/_/   |_|_____|  %\n'),
write('%                                              %\n'),
write('%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%\n').

/* Biar ada jeda gitu */
p1 :- sleep(1).
p2 :- sleep(2).
p3 :- sleep(3).

win_screen :-
nl, p1, 
write('=================================###############################====================================\n'),
write('============================#####   You\'ve Reached Your Goal   #####===============================\n'),
write('======================######                                         ######=========================\n'), p2,
write('       ###                                                                                          \n'),
write('       ###                                                                                          \n'),
write('       ###                                                                                          \n'),
write('       ###                                                                                          \n'),
write('       ###                                                                                          \n'),
write('       ###                                                                                          \n'),
write('       ###                                                                                          \n'),
write('       ###                                                                                          \n'),
write('       ###                                                                                          \n'),
write('       +++                                                                                          \n\n'), p2,
write('        Tak terasa setahun telah berlalu...\n'), p1,
write('        Berbagai macam rintangan dan cobaan telah Claire jalani\n'), p1,
write('        Jauh berbeda rasanya kehidupan di Desa bagi Claire\n\n'), p3,
write('        Claire berpikir, mungkin musibah tahun lalu ada maknanya juga.\n\n'), p3,
write('        Kenangan jerih payah kakeknya di Desa menjadi jelas dan terang\n'), p1,
write('        Kehidupan harmonis bersama-sama ternyata dapat dicapai\n'), p1,
write('        Pengalaman setahun ini akan menjadi harta berharga bagi Claire,\n\n'), p2,
write('        Untuk selamanya...\n\n'), p3,
write('                                                                                                    \n'),
write('                                             ,,,,,ggggg,,,,,                                        \n'),
write('                                     ,,g@@NP*""``       `""^*MNB@Ngg,                               \n'),
write('                                  g@@N"                            `*MB@g,                          \n'),
write('                               ,@@P`                            g       `*B@w                       \n'),
write('                             g@@"                         @@   ]@g          *B@w                    \n'),
write('                           g@@`                @F      ..@g   @@@K             @w                   \n'),
write('                          @@`                    g@   g@P @   @P]@p  @           @g                 \n'),
write('                        @@          /          ,@@C  @@`  $  ]@  ]@  @@   *lL,   "B@                \n'),
write('                        @@         g  ``       g@@@ ,@@    $  @[   B@ ]@@          L]@g             \n'),
write('                       @@         j          ,@@@@@@@@w,   @ @@     @C]$@@       ,  ]@k             \n'),
write('                    ,gg@@ggg,     ]    ,gW@@@P`@@@@` " N ]@]@C     @]@]@             ]@C            \n'),
write('           ,g@@NNNB@@@$**gg&*@P   TL    @@j@@` ]@@@       ]@@K       @@@NB@g       T`  ]@           \n'),
write('       ,g@N"        `%@@J@@,g@P    lL ,@@y@@   @@$,       ]@@        %@@ ]@R@Ng         @L          \n'),
write('     ,@@" ,+          ]@`NN@@@P    lg@@@@@Pg@@@@NB@@b     ]@         ]@P  B@]@@       @p$@          \n'),
write('    @@"   *           ]@PMMMP*wgr ]j@@`@@$@@PB@@@@ "@@               ,,,, ]@ ]@C      @@]@          \n'),
write('  ,@@               , $@L]M,g@@@  ]@"  MQ@@@@g@@@@@ ^^            g@@@Q*@@U@U@@@     ]@@@@^^        \n'),
write(' g@@               @|$@@@,@@@wg@  @[    ]@@@@@@@@@@              @@"$@@@ @@$@@$@ g   ]@*@@g         \n'),
write('   $K   g    ]^^^^^,^@@ $@@@P]@@  @h    [$@@@@@@@@@             @@@@@@@@ ]@]NV@@@@   @P `@W^^       \n'),
write('   @K,gp    ]|    |`]@  ]@*"]@$%  @P     $@@@@@@@@@            ]@@@@@@@@ @@  @@@@@  ]@      %@g     \n'),
write('  ]@@@$@g   #L|g ] g@[  ]@  ][]@  @       @@@@@@@@             ]@@@@@@@@]R  ]@P@@%@u@h       "Bb    \n'),
write('  ``  ]@@@,    |W@ @@@   %@ "*]$ ]@        "^^^"               ]@@@@@@@     @@,@@@@@@         g@K   \n'),
write('       ` ]@N|gg,  `@C     ]@W  @ ]@                             `*MM*`     @@@@@|k]N          @@@   \n'),
write('            @@*B@@@@@        *B@@K]@                                       ]@@Q@@p l@      ^ ^^^    \n'),
write('                               B@#@g                                      ]@@@P]@p,|$g ,   ]@B@P^^  \n'),
write('                                @@@@@,            g@@Ngg,,,               [[$L  ]@@@@p|)@  @@       \n'),
write('                                ]@R@@@@,         @@     ]@@               [[@L   ]@["B@@B@@@        \n'),
write('                                    %@Q%@g,      ;       @@              ,@K@P        "  ^"         \n'),
write('                                     ]@W@P%@N,   ,k    ,@F          ,,g@@N@]@                       \n'),
write('                                   g@@RB@P  `*B@N@$    "` ,,,ggg@@BR*"`   @@@                       \n'),
write('                        g@@NB@@**N@"   g,        "****@@@@K"`             @@                        \n'),
write('                   ,gg@@@@   "@N  B@   ]@,            @@g@*MMMM%@P"@@B@g,,"`                        \n'),
write('       gggg      g@N"    ]@,  "@K  N@   "@b           *"N@C     %@ ]@ $@""RB@,                      \n'),
write('       $@ "B@g,,@@   ,,   ]@g   @K  B@    %@, ,,ggg@@@N@N@@      @L $K]M    "@K                     \n'),
write('        *@b, "N@@g   ]gg    @b   @@   @     B@P"@@B@Nw,  "$K     ]@ ]@ *r    "@k                    \n'),
write('          "%@N,  *N@g,]$g    N@   B@  ]@,    %@,@bg,  "*B@@@,     $r]@ MC  ,L "@k                   \n'),
write('            ,@N@N,  `*B@@bgggg%@,  %@, "B@    "@b "*%@Ng,  "*N@Nw,$@,@,|[  ]g,,"@@N                 \n'),
write('            @P  @@@    ,g""   "*%@g,"Bb  %@N    %@     "*B@Ng   `*M" `"*NN@@@@[ ]@%@g               \n'),
write('           @@   *   $BM*` ,,,     "@g *@N  %@N   ]@g      @@"%@        RNL "B@,  ]@P@b              \n'),
write('          g@    ]@g  @g@@@`"*     ]@b, *B@, *B@, "B@,,   "@@w               "Bb  TL @,              \n'),
write('         ]@`   ]$ "4@Ngg@N$         ]$@@N,`%@N,`N@@@"`$@@@N@@@                 ]@Wgg, ]@W           \n'),
write('         @@     $@gg  g@  ]@,        $@ "N@bg"N@@P ,@@^M*  j@                    B@C*N@gB@          \n'),
write('        ]@      ,, "^*P    "NL       [@    , @@P  /@P,BP#g,p@@                   ]@   " @@@         \n'),
write('        @[      `"*N@w,              @K ,@@P     g@k@N| ]@@R@@W                  @K       @@        \n'),
write('       ]@           ,]@@w            BBg*B@Nw,   RRP  | $@#@]@* @Bg             @@         ]@N      \n'),
write('       @[         ,@P`  ]$M*        ]~,@N  g@@          @@D@pN@  ]*@@Ngg,,    ,@P          ]l*@b    \n'),
write('                                                                                                    \n'),
write('         .d8888b.   .d88888b.   .d88888b.  8888888b.       8888888888 888b    888 8888888b.         \n'),
write('        d88P  Y88b d88P^ ^Y88b d88P^ ^Y88b 888  ^Y88b      888        8888b   888 888  ^Y88b        \n'), 
write('        888    888 888     888 888     888 888    888      888        88888b  888 888    888        \n'),
write('        888        888     888 888     888 888    888      8888888    888Y88b 888 888    888        \n'),
write('        888  88888 888     888 888     888 888    888      888        888 Y88b888 888    888        \n'),
write('        888    888 888     888 888     888 888    888      888        888  Y88888 888    888        \n'),
write('        Y88b  d88P Y88b. .d88P Y88b. .d88P 888  .d88P      888        888   Y8888 888  .d88P        \n'),
write('         ^Y8888P88  ^Y88888P^   ^Y88888P^  8888888P^       8888888888 888    Y888 8888888P^         \n'),
write('                                                                                                    \n'),
write('                                                                                                    \n'),
write('                                                                                                    \n'),
write('                                                                                                    \n'),
write('                                                                                                    \n'),
write('      Thanks for trying out our game!\n'),
write('      We are the - Surya Pro Log -\n'),
write('        -   Suryanto (13520059)\n'),
write('        -   Raden Haryosatyo Wisjnunandono (13520070)\n'),
write('        -   Farrel Ahmad (13520110)\n'),
write('        -   Muhammad Rakha Athaya (13520108)\n').

lose_screen :-
nl, p1, 
write('=================================###############################====================================\n'),
write('============================#####         You\'ve Failed        #####===============================\n'),
write('======================######                                         ######=========================\n'), p2,
write('       ###                                                                                          \n'),
write('       ###                                                                                          \n'),
write('       ###                                                                                          \n'),
write('       ###                                                                                          \n'),
write('       ###                                                                                          \n'),
write('       ###                                                                                          \n'),
write('       ###                                                                                          \n'),
write('       ###                                                                                          \n'),
write('       ###                                                                                          \n'),
write('       +++                                                                                          \n\n'), p2,
write('        Kenapa setahun berlalu sangat cepat???\n'), p1,
write('        Berbagai cara sudah Claire usahakan\n'), p1,
write('        Namun tetap akhirnya gagal juga\n\n'), p3,
write('        Claire berpikir, mungkin ini memang sudah takdirku.\n\n'), p3,
write('        Teman, keluarga,... semuanya hanya tinggal kenangan\n'), p1,
write('        Kehidupan Claire sebelum tahun lalu tidak bisa kembali lagi\n'), p1,
write('        Sudahlah, Claire pikir, lebih baik aku akhiri saja,\n\n'), p2,
write('        Segalanya...\n\n'), p3,
write('                                                                                                    \n'),
write('                                  ,,ggggggNNNNgggpgg,,                                              \n'),
write('                            ,g@@R*^`                `^*MN@Ngg,                                      \n'),
write('                       ,g@@P^                       `^^^ l+,^*B@Ng                                  \n'),
write('                    ,g@N^           ,, ,=               `^^   l> ^B@g,                              \n'),
write('                 ,g@P`             jg@P                      ^*L    ^B@w                            \n'),
write('               ,@@^                g@QF    #@                          %@W                          \n'),
write('              @@^ ,          @@  |]@`@C    j@K    B@                     %@                         \n'),
write('            /@P,w ^     , ` @@P |,@h $@  L $@@K   ]@@                     ]@                        \n'),
write('           g@`,  `     i^` @@@  ^@@  ]@    ][^@@   %@@,                 ,gg@@g,,                    \n'),
write('          @@    `     ,   @@]@  @@    $@ L ]@  B@,  B@@W   ^         ]@@@$@$@$$$[                   \n'),
write('         ]@`   L     ]$L @@ ]@ ]@P     @K  ]@   ]@b  @@N@  @@ ,      ]@$$$@@]$@@P*^^*N@@w,          \n'),
write('         @h          @[ ]@  ]@ @@      ^@K  @W@@P^%@N^@N]@w]@@  ,    ]@@@M@M]@F  ^* L,  ^%@g        \n'),
write('        ]@   L      ,@[ @hBB&@N@bw      ^@@ @[      *B@@@ N@@@@, L   ]@@P%%$@@       *  &, %@g      \n'),
write('       ,@[|         *@[@@    ]@@          B@@@  g@@@@B@@@@,^B@R@W^    ^^***R@   ,      !     B@     \n'),
write('      @@@P          $@@@P,ggN@@@           *@@b@@$@@@Bw ^%@@g**^B@        ]]@|r               ]@,   \n'),
write('     @P @   ^      ]@R@@@@P)m@l|m,           **@@`    *@k  %@K   ]@  g   ,|j@ [                ]@g  \n'),
write('    @@^ $P@[       $@ $@@ @@     %@           ]T        $C  $@   ]@  @@@B@@ @K|                @@@K \n'),
write('   @@   @N@@    ]@ @K @@ ]T       %@          ]^        ]@  ]@   ]@  Nwggg$@@@|k             ,,@P^* \n'),
write('  j@P | ]@@@     $j@C @P ]l        lr         ],        ]   ]@   ][ ]@@@g^%$@@K`           ]N@@@    \n'),
write('  ]@   L]@MB@    @@@@ @@ ]$         F         ]l        ]&       #[ ]@  lC]l@]@w@  @g    ,,@@@      \n'),
write('  @P  ^` $@]@g   %@/@C]@r %@      ,@F          %b      g@`       @[ $@k ,L ]@ ]@@@w|j@@@@@@^        \n'),
write('  @@      ` ]@g g/NC$@     B@,  ,g@P            *B@g@@N^         @L @@F R ,@P  ]@@^*NN              \n'),
write(' %F@U@@      ]@@@@gr]@      `****^                           ,   @P]@   ,@@`                        \n'),
write('   ]@PBN@@@,,g|N@@@K @P                                     ]%@P @P]@g@@P`                          \n'),
write('       ^  B@@ggg@@@@|@P                                     ]&lP @L@@@                              \n'),
write('            ^^%N` %@p@                   ,,,ggggggBB@@N      ^^ /@@@P                               \n'),
write('                   ]@@p           $@@@@*^^^`         ^$p      ,@@@@F                                \n'),
write('                    @B@N          ]@@@                ]@    ,@@@@@@                                 \n'),
write('                    ]@@^B@g,      ]@@                 ]@gg@@@@@@`                                   \n'),
write('                     $@    ^*N@Ngg,@@            ,,g@@BP$@@@NNR@Ng                                  \n'),
write('                      ^           `^$@@NB@@@@@BNM*^     %@@     ]@B@w                               \n'),
write('                                 ,@@@`   ]@]@P           $@     @K  ^B@p                            \n'),
write('                              ,@@P`]@    ]M^,g@@@%%B@@Bgg@K    g@    ]@*B@,                         \n'),
write('                            ,@@$@   @     NP^           g@    g@`   ,@P @@^B@w                      \n'),
write('                           @@]$ @C  %@    $K           ]@`   g@`   ,@K @@    %@,                    \n'),
write('                         ,@P  @C]@   $@   ]$          ,@C  ,@@    g@P,@P      ]@C                   \n'),
write('                        ,@P   ]@ ]@   B@   $@        ,@F  g@C   g@@ g@^      ]W]@                   \n'),
write('                        @K@    ]@p]@p  B@pgg$@gggggg@@%g@@P  ,g@P g@P       ,@C ]@                  \n'),
write('                       @@ @C    ]@g]@gg@@  ]@@` @@@     B@,g@@^,@@*         @P   BK                 \n'),
write('                      ]@  $@     ^B@]@@`,g@@@@  @M@@@,   %@Cg@@P`          @@    ]@                 \n'),
write('                      @P  ]@]@     ]@P,@@$@Kg@@@@$@@@@b   ]@C           gm]$      ]@                \n'),
write('                                                                                                    \n'),
write('              888888b.         d8888 8888888b.       8888888888 888b    888 8888888b.               \n'),
write('              888  ^88b       d88888 888  ^Y88b      888        8888b   888 888  ^Y88b              \n'), 
write('              888  .88P      d88P888 888    888      888        88888b  888 888    888              \n'),
write('              8888888K.     d88P 888 888    888      8888888    888Y88b 888 888    888              \n'),
write('              888  ^Y88b   d88P  888 888    888      888        888 Y88b888 888    888              \n'),
write('              888    888  d88P   888 888    888      888        888  Y88888 888    888              \n'),
write('              888   d88P d8888888888 888  .d88P      888        888   Y8888 888  .d88P              \n'),
write('              8888888P^ d88P     888 8888888P^       8888888888 888    Y888 8888888P^               \n'),
write('                                                                                                    \n'),
write('                                                                                                    \n'),
write('                                                                                                    \n'),
write('                                                                                                    \n'),
write('                                                                                                    \n'),
write('      Thanks for trying out our game!\n'),
write('      We are the - Surya Pro Log -\n'),
write('        -   Suryanto (13520059)\n'),
write('        -   Raden Haryosatyo Wisjnunandono (13520070)\n'),
write('        -   Farrel Ahmad (13520110)\n'),
write('        -   Muhammad Rakha Athaya (13520108)\n').